server:
  port: 4003

logging:
  level:
    root: info

grpc:
  server:
    port: 8003

spring:
  application:
    name: analytics-service
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer

